#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Aliases
#

# exa
alias ls='exa -g'
alias ll='exa -lag'
alias la='exa -a'
alias lsnew='exa -lagsnew'
alias sl='/usr/local/bin/sl'

# bat
alias cat='bat'
# nvim
alias v=nvim
alias vi=nvim
alias vim=nvim

#
# Tools
#

# FZF
[ -f ~/.config/fzf/.fzf.zsh ] && source ~/.config/fzf/.fzf.zsh

# fasd
eval "$(fasd --init auto)"
