# Dotless home directory

if [[ -z $XDG_CONFIG_HOME ]]; then
    export XDG_CONFIG_HOME=$HOME/.config
fi

if [[ -z $XDG_CACHE_HOME ]]; then
    export XDG_CACHE_HOME=$HOME/.cache
fi

if [[ -z $XDG_DATA_HOME ]]; then
    export XDG_DATA_HOME=$HOME/.local/share
fi

# zsh
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# fasd
# export _FASD_DATA=$XDG_CONFIG_HOME/fasd/.fasd

# less
export LESSHISTFILE=${XDG_CONFIG_HOME}/less/history
export LESSKEY=${XDG_CONFIG_HOME}/less/keys

# vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/nvim/init.vim" | source $MYVIMRC'
export VIMDOTDIR=$XDG_CONFIG_HOME/nvim

