# ~/.zshrc

# starship
eval "$(starship init zsh)"

# VIM mode
bindkey -v

# zsh options
setopt auto_cd
setopt correct_all

# zsh-autocomplete
zstyle ':autocomplete:*' min-input 5   # int
zstyle ':autocomplete:*' min-delay 0.5 # float
zstyle ':autocomplete:*' widget-style menu-select
source ~/.config/zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# zsh-autosuggestions
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#8f8f8f"

# zsh-syntax-highlighting
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')

# exa
alias ls='exa -bgF'
alias ll='exa -laabgF'
alias la='exa -aaF'
alias sl='/usr/local/bin/sl'

# bat
alias cat='bat'

# Safe rm
[ -f /usr/local/bin/trash ] && alias rm="/usr/local/bin/trash"

# nvim
alias vi=nvim
alias vim=nvim

# python
alias python=/usr/local/bin/python3

# FZF
[ -f ~/.config/fzf/.fzf.zsh ] && source ~/.config/fzf/.fzf.zsh

# fasd
eval "$(fasd --init posix-alias zsh-hook zsh-wcomp)"
alias v='f -e nvim' # quick opening files with vim
