# ~/.zshrc

# Download Znap, if it's not there yet.
[[ -f ~/.config/zsh/zsh-snap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/.config/zsh/zsh-snap

# Start Znap
source ~/.config/zsh/zsh-snap/znap.zsh

# starship
znap eval starship 'starship init zsh'
znap prompt

# VIM mode
bindkey -v

# zsh options
setopt AUTO_CD
setopt CORRECT_ALL
setopt NO_CASE_GLOB # MacOS is case insensitive
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS

# zsh-autocomplete
zstyle ':autocomplete:*' min-input 5   # int
zstyle ':autocomplete:*' min-delay 0.5 # float
zstyle ':autocomplete:*' widget-style menu-select
znap source marlonrichert/zsh-autocomplete

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#8f8f8f"
znap source zsh-users/zsh-autosuggestions

# zsh-syntax-highlighting
typeset -A ZSH_HIGHLIGHT_PATTERNS
ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
znap source zsh-users/zsh-syntax-highlighting

# FZF
[ -f ~/.config/fzf/.fzf.zsh ] && source ~/.config/fzf/.fzf.zsh

# fasd
eval "$(fasd --init posix-alias zsh-hook zsh-wcomp)"

# exa
if command -v exa > /dev/null; then
    alias ls='exa -bgF'
    alias ll='exa -laabgF'
    alias la='exa -aaF'
fi

# bat
if command -v bat > /dev/null; then
    alias cat=bat
fi

# Safe rm
if command -v trash > /dev/null; then
    alias rm=trash
fi

# nvim
if command -v nvim > /dev/null; then
    alias vi=nvim
    alias vim=nvim
fi

# python
alias python=python3
